# ==============================================================================
# SCRIPT: 04_validate_gene_filtering.R
#
# PURPOSE:
#   This script serves as a critical quality control and validation step. To
#   ensure the reliability of our noise calculations in the previous script,
#   we applied stringent filtering to remove genes with very low or sparse
#   expression, as these can produce spurious noise estimates.
#
#   This script's purpose is to create a diagnostic plot that visually
#   justifies these filtering criteria by showing the relationship between
#   mean expression and the coefficient of variation (CV), highlighting which
#   gene-celltype pairs were kept and which were discarded.
# ==============================================================================

# --- 1. SETUP: Load libraries and define paths ---

# Load packages required for data manipulation and plotting
packages_to_load <- c("dplyr", "ggplot2", "scales")
for (pkg in packages_to_load) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org/")
  }
  library(pkg, character.only = TRUE)
}

# --- Define I/O Paths ---
# INPUT: The complete, unfiltered noise data generated by script 03 (UPDATED PATH)
complete_noise_data_path <- "/group/sms029/mnieuwenh/gbm_noise_analysis/results/03_calculate_expression_noise/03_gene_noise_metrics_complete.csv"

# OUTPUT: The directory for this script's validation plots (UPDATED PATH)
output_dir <- "/group/sms029/mnieuwenh/gbm_noise_analysis/results/04_validate_gene_filtering"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Define the full path for the output plot (UPDATED FILENAME)
filter_plot_path <- file.path(output_dir, "04_filtering_criteria_visualization.png")


# --- 2. DATA LOADING AND PREPARATION ---

message("Loading complete noise data to visualize filtering effects...")
if (!file.exists(complete_noise_data_path)) {
  stop(paste("Error: Input data file not found at", complete_noise_data_path))
}
noise_data <- read.csv(complete_noise_data_path)

message("Preparing data for plotting by assigning filter status...")
# Create a new column 'filter_status' to categorize each gene-celltype pair
# based on the criteria used in script 03.
plot_data <- noise_data %>%
  filter(is.finite(mean_expr) & mean_expr > 0 & is.finite(cv2) & cv2 > 0) %>%
  mutate(
    cv = sqrt(cv2), # Calculate CV from CV^2
    filter_status = case_when(
      mean_expr > 0.01 & pct_expressing > 0.1 ~ "Passed",
      mean_expr <= 0.01 & pct_expressing > 0.1 ~ "Filtered (Low Mean Expression)",
      mean_expr > 0.01 & pct_expressing <= 0.1 ~ "Filtered (Low Detection Rate)",
      TRUE ~ "Filtered (Both)"
    )
  ) %>%
  # Set the factor levels for a logical order in the plot legend
  mutate(filter_status = factor(
    filter_status,
    levels = c("Passed", "Filtered (Low Detection Rate)", "Filtered (Low Mean Expression)", "Filtered (Both)")
  ))

# For efficient plotting, we will plot all points that passed the filter,
# but only a representative sample of the points that were filtered out.
passed_data <- plot_data %>% filter(filter_status == "Passed")
filtered_data <- plot_data %>% filter(filter_status != "Passed")

# Set a seed for reproducibility of the sampling
set.seed(123)
# If there are many filtered points, sample them to avoid a cluttered and slow plot
if (nrow(filtered_data) > 200000) {
  sampled_filtered_data <- filtered_data %>% sample_n(200000)
} else {
  sampled_filtered_data <- filtered_data
}

# Combine the 'passed' data with the 'sampled filtered' data for the final plot
plot_data_sampled <- bind_rows(passed_data, sampled_filtered_data)

message(paste(
  "Plotting", nrow(plot_data_sampled), "data points (all",
  nrow(passed_data), "passing points, and a sample of filtered points)."
))


# --- 3. CREATE AND SAVE THE VISUALIZATION ---

message("Generating the mean vs. CV plot to visualize filter effects...")

# Define a color palette for the different filter statuses
filter_colors <- c(
  "Passed" = "black",
  "Filtered (Low Detection Rate)" = "lightskyblue",
  "Filtered (Low Mean Expression)" = "salmon",
  "Filtered (Both)" = "plum"
)

p <- ggplot(plot_data_sampled, aes(x = mean_expr, y = cv, color = filter_status)) +
  geom_point(size = 0.5, alpha = 0.4) +
  # Add a line representing the theoretical shot noise limit (CV = 1/sqrt(Mean))
  geom_function(
    fun = function(x) 1/sqrt(x),
    color = "darkred",
    linetype = "dashed",
    linewidth = 1
  ) +
  # Add a vertical line showing the mean expression filter threshold
  geom_vline(xintercept = 0.01, linetype = "dotted", color = "gray40", linewidth = 0.8) +
  # Use log scales for both axes to better visualize the wide range of values
  scale_x_log10(
    labels = trans_format("log10", math_format(10^.x)),
    breaks = 10^seq(-4, 4, by = 2)
  ) +
  scale_y_log10(
    labels = trans_format("log10", math_format(10^.x)),
    breaks = 10^seq(-2, 4, by = 2)
  ) +
  scale_color_manual(values = filter_colors) +
  # Improve legend readability
  guides(color = guide_legend(override.aes = list(size = 3, alpha = 1))) +
  # Add annotations directly to the plot for clarity
  annotate("text", x = 10, y = 0.05, label = "Shot Noise\n(CV = 1/sqrt(Mean))", color = "darkred", hjust = 0) +
  annotate("text", x = 0.008, y = 1000, label = "Mean Expr = 0.01", color = "gray40", angle = 90, hjust = 1, vjust = -0.5) +
  labs(
    title = "Validation of Gene Filtering Criteria",
    subtitle = paste("Showing", format(nrow(passed_data), big.mark=","), "gene-celltype pairs that passed filters for noise analysis"),
    x = "Mean Gene Expression (Linear Scale, Plotted on Log Axis)",
    y = "Coefficient of Variation (CV = SD / Mean, Plotted on Log Axis)",
    color = "Filter Status"
  ) +
  theme_bw(base_size = 14) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    plot.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

message(paste("Saving plot to:", filter_plot_path))
ggsave(filter_plot_path, plot = p, width = 12, height = 9, dpi = 300)

# --- 4. FINAL CONFIRMATION ---
summary_text <- c(
  "Filter Visualization Script Complete.",
  "",
  "A diagnostic plot showing the effect of data filtering has been generated.",
  "This plot validates the filtering criteria used for the main noise analysis:",
  "  - Mean Expression > 0.01",
  "  - Percentage of Expressing Cells > 0.1",
  "",
  paste("The plot has been saved to:", filter_plot_path)
)
# Save a text summary of the script's output
writeLines(summary_text, file.path(output_dir, "04_filtering_visualization_summary.txt"))

message("Script finished successfully.")