configfile: "config/config.yaml"

RESULTS = config["output_dir"]

rule all:
    input:
        f"{RESULTS}/00_overview/00_data_summary.txt",
        f"{RESULTS}/01_epigenetics/epigenetic_annotations.csv",
        f"{RESULTS}/01_epigenetics/summary.txt",
        f"{RESULTS}/02_export/expression_matrix.mtx.gz",
        f"{RESULTS}/02_export/genes.tsv.gz",
        f"{RESULTS}/02_export/cell_metadata.csv",
        f"{RESULTS}/03_noise/noise_per_identity.csv.gz",
        f"{RESULTS}/03_noise/noise_summary.txt",
        f"{RESULTS}/04_filter_qc/filter_qc.png",
        f"{RESULTS}/04_filter_qc/filtering_summary.txt",
        f"{RESULTS}/05_responsive/global_summary.txt",
        f"{RESULTS}/05_responsive/noise_with_responsiveness.csv.gz",
        f"{RESULTS}/05_responsive/global_plots.png",
        f"{RESULTS}/06_models/global_model_summary.txt",
        f"{RESULTS}/06_models/meta_analysis.txt",
        f"{RESULTS}/06_models/global_figure.png",
        f"{RESULTS}/07_enrichment/gsea_summary.txt",
        f"{RESULTS}/07_enrichment/gsea_global.png",
        f"{RESULTS}/08_bootstrap/bootstrap_summary.txt",
        f"{RESULTS}/08_bootstrap/bootstrap_coeffs.png",
        f"{RESULTS}/08_bootstrap/bootstrap_table.csv"

rule overview:
    input:
        cahn=config["methylation"]["cahn_csv"],
        bewick=config["methylation"]["bewick_csv"],
        seurat=config["seurat_rds"]
    output:
        txt=f"{RESULTS}/00_overview/00_data_summary.txt"
    conda: "envs/r_base.yaml"
    threads: 2
    resources:
        mem_mb=8000, time="01:00:00"
    shell:
        "Rscript scripts/00_overview.R --cahn {input.cahn} --bewick {input.bewick} --seurat {input.seurat} --outdir {RESULTS}/00_overview"

rule epigenetics:
    input:
        cahn=config["methylation"]["cahn_csv"],
        bewick=config["methylation"]["bewick_csv"],
        h2az_dep=config["methylation"]["h2az_dep"],
        h2az_enr=config["methylation"]["h2az_enr"]
    output:
        csv=f"{RESULTS}/01_epigenetics/epigenetic_annotations.csv",
        txt=f"{RESULTS}/01_epigenetics/summary.txt"
    conda: "envs/r_base.yaml"
    threads: 4
    resources:
        mem_mb=32000, time="08:00:00"
    shell:
        "Rscript scripts/01_epigenetics.R --cahn {input.cahn} --bewick {input.bewick} --h2az_dep {input.h2az_dep} --h2az_enr {input.h2az_enr} --outdir {RESULTS}/01_epigenetics --genome {config[reference][bsgenome]} --txdb {config[reference][txdb]} --use_araport11 {config[reference][use_araport11]} --jaspar_id {config[reference][jaspar_tata_id]} --pwm_min_score {config[reference][pwm_min_score]}"

rule export_expr:
    input:
        seurat=config["seurat_rds"]
    output:
        mtx=f"{RESULTS}/02_export/expression_matrix.mtx.gz",
        genes=f"{RESULTS}/02_export/genes.tsv.gz",
        cells=f"{RESULTS}/02_export/cell_metadata.csv"
    conda: "envs/r_base.yaml"
    threads: 4
    resources:
        mem_mb=64000, time="08:00:00"
    shell:
        "Rscript scripts/02_export.R --seurat {input.seurat} --outdir {RESULTS}/02_export"

rule noise_per_identity:
    input:
        mtx=f"{RESULTS}/02_export/expression_matrix.mtx.gz",
        genes=f"{RESULTS}/02_export/genes.tsv.gz",
        cells=f"{RESULTS}/02_export/cell_metadata.csv",
        anno=f"{RESULTS}/01_epigenetics/epigenetic_annotations.csv"
    output:
        csv=f"{RESULTS}/03_noise/noise_per_identity.csv.gz",
        txt=f"{RESULTS}/03_noise/noise_summary.txt"
    conda: "envs/r_base.yaml"
    threads: 8
    resources:
        mem_mb=128000, time="24:00:00"
    shell:
        "Rscript scripts/03_noise_per_identity.R --mtx {input.mtx} --genes {input.genes} --cells {input.cells} --anno {input.anno} --outdir {RESULTS}/03_noise --min_cells {config[noise][min_cells_per_identity]} --max_cells {config[noise][max_cells_per_identity]} --min_mean {config[noise][min_mean_expr]} --min_pct {config[noise][min_pct_expressing]}"

rule filter_qc:
    input:
        csv=f"{RESULTS}/03_noise/noise_per_identity.csv.gz"
    output:
        fig=f"{RESULTS}/04_filter_qc/filter_qc.png",
        txt=f"{RESULTS}/04_filter_qc/filtering_summary.txt"
    conda: "envs/r_base.yaml"
    threads: 2
    resources:
        mem_mb=16000, time="02:00:00"
    shell:
        "Rscript scripts/04_filter_qc.R --noise {input.csv} --outdir {RESULTS}/04_filter_qc --min_mean {config[noise][min_mean_expr]} --min_pct {config[noise][min_pct_expressing]}"

rule responsive:
    input:
        seurat=config["seurat_rds"],
        noise=f"{RESULTS}/03_noise/noise_per_identity.csv.gz"
    output:
        txt=f"{RESULTS}/05_responsive/global_summary.txt",
        csv=f"{RESULTS}/05_responsive/noise_with_responsiveness.csv.gz",
        fig=f"{RESULTS}/05_responsive/global_plots.png"
    conda: "envs/r_base.yaml"
    threads: 8
    resources:
        mem_mb=96000, time="24:00:00"
    shell:
        "Rscript scripts/05_responsive.R --seurat {input.seurat} --noise {input.noise} --outdir {RESULTS}/05_responsive"

rule models:
    input:
        csv=f"{RESULTS}/05_responsive/noise_with_responsiveness.csv.gz"
    output:
        txt=f"{RESULTS}/06_models/global_model_summary.txt",
        fig=f"{RESULTS}/06_models/global_figure.png",
        meta=f"{RESULTS}/06_models/meta_analysis.txt"
    conda: "envs/r_base.yaml"
    threads: 8
    resources:
        mem_mb=96000, time="12:00:00"
    shell:
        "Rscript scripts/06_models.R --csv {input.csv} --outdir {RESULTS}/06_models"

rule enrichment:
    input:
        csv=f"{RESULTS}/05_responsive/noise_with_responsiveness.csv.gz"
    output:
        txt=f"{RESULTS}/07_enrichment/gsea_summary.txt",
        fig=f"{RESULTS}/07_enrichment/gsea_global.png"
    conda: "envs/enrich.yaml"
    threads: 2
    resources:
        mem_mb=24000, time="06:00:00"
    shell:
        "Rscript scripts/07_enrichment.R --csv {input.csv} --outdir {RESULTS}/07_enrichment"

rule bootstrap:
    input:
        csv=f"{RESULTS}/05_responsive/noise_with_responsiveness.csv.gz"
    output:
        txt=f"{RESULTS}/08_bootstrap/bootstrap_summary.txt",
        fig=f"{RESULTS}/08_bootstrap/bootstrap_coeffs.png",
        table=f"{RESULTS}/08_bootstrap/bootstrap_table.csv"
    conda: "envs/r_base.yaml"
    threads: 8
    resources:
        mem_mb=64000, time="12:00:00"
    shell:
        "Rscript scripts/08_bootstrap.R --csv {input.csv} --outdir {RESULTS}/08_bootstrap"